#!/bin/sh
# Copyright (C) 2017, iZotope, Inc. All Rights Reserved
# Released under the BSD-3 license (see COPYING.BSD-3)

# A script for very fast cleanup before shutdown or reboot

cd /etc/init.d

echo "Sending all processes the TERM signal..."
killall5 -15

# Everyone gets at least 1s to shut down
sleep 1

# GamutApp and GamutHelper must shut down gracefully
./gamut-app stop
./gamut-helper stop

# Everyone else is on their own
killall5 -9

./hwclock.sh stop
./alsa-state stop
./umountnfs.sh
./umountfs
