#!/bin/sh
# Copyright (C) 2017, iZotope, Inc. All Rights Reserved
# Released under the BSD-3 license (see COPYING.BSD-3)

FREQ_DIR=/sys/devices/system/cpu/cpu0/cpufreq

MAX_FREQ=`cat $FREQ_DIR/cpuinfo_max_freq`

echo $MAX_FREQ > $FREQ_DIR/scaling_setspeed

FREQ=`cat $FREQ_DIR/cpuinfo_cur_freq`

if [ "$MAX_FREQ" != "$FREQ" ]; then
	echo "Couldn't set CPU to max freq, $MAX_FREQ, set at $FREQ"
	exit 1
fi

echo "Set CPU frequency to max: $FREQ"
